sudo: required
dist: trusty
language: java
jdk:
- oraclejdk8
install:
- mvn -N io.takari:maven:wrapper -Dmaven=3.5.0
- java -version && javac -version && ./mvnw -version -B
- git clone https://github.com/garethahealy/camel-mapstruct.git
- ./mvnw clean install -f camel-mapstruct/pom.xml -DskipTests
- rm -rf camel-mapstruct
before_script:
- ./mvnw dependency:go-offline -B
script:
- ./mvnw clean install -B -Dgpg.skip=true
cache:
  directories:
  - $HOME/.m2
  - $HOME/.victims
